import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'Analyze Now',
    newAnalysis: 'New Analysis',
    
    // Home Page
    heroLabel: 'Advanced AI Forensics',
    heroTitle: 'Detect AI Content & Scam Threats',
    heroDescription: 'VeriSure provides forensic-grade analysis to identify AI-generated content and assess scam risk. Protect yourself from deepfakes, manipulated media, and social engineering attacks targeting Indians.',
    getStarted: 'Get Started',
    howItWorks: 'How It Works',
    safe: 'Safe',
    warning: 'Warning',
    danger: 'Danger',
    
    // Analysis Page
    forensicAnalysis: 'Forensic Analysis',
    submitContent: 'Submit Content for Analysis',
    submitDescription: 'Upload files, paste text, or provide URLs. VeriSure will analyze for AI origin and scam indicators.',
    upload: 'Upload',
    text: 'Text',
    url: 'URL',
    clickToUpload: 'Click to upload or drag and drop',
    fileTypes: 'PNG, JPG, MP4, MOV (max 50MB)',
    pasteText: 'Paste suspicious text, messages, or content here...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'Enter a URL pointing to an image, video, or webpage for analysis',
    cancel: 'Cancel',
    analyze: 'Analyze Now',
    analyzing: 'Analyzing...',
    recordVoice: 'Record Voice',
    stopRecording: 'Stop Recording',
    listening: 'Listening...',
    
    // Results Page
    analysisReport: 'Analysis Report',
    forensicComplete: 'Forensic Analysis Complete',
    highRisk: 'HIGH RISK - LIKELY SCAM',
    highRiskWarning: 'DO NOT respond or share any information!',
    mediumRisk: 'MEDIUM RISK - Be Careful',
    lowRisk: 'LOW RISK - Appears Safe',
    originClassification: 'Origin Classification',
    confidence: 'confidence',
    indicators: 'Indicators',
    scamRisk: 'Scam Risk Level',
    patternsDetected: 'Patterns Detected',
    evidenceSummary: 'Evidence Summary',
    signalsDetected: 'Signals Detected',
    forensicNotes: 'Forensic Notes',
    reportDetails: 'Report Details',
    reportId: 'Report ID',
    timestamp: 'Timestamp',
    contentHash: 'Content Hash (SHA-256)',
    recommendedActions: 'Recommended Actions',
    analysisSummary: 'Analysis Summary',
    limitations: 'Limitations',
    readAloud: 'Read Aloud',
    shareWhatsApp: 'Share on WhatsApp',
    
    // Risk Levels
    highRiskLabel: 'HIGH RISK',
    mediumRiskLabel: 'MEDIUM RISK',
    lowRiskLabel: 'LOW RISK',
    
    // Toast Messages
    fileSelected: 'File selected',
    selectFile: 'Please select a file to upload',
    enterText: 'Please enter text to analyze',
    enterUrlText: 'Please enter a URL to analyze',
    analysisComplete: 'Analysis complete!',
    analysisFailed: 'Analysis failed. Please try again.',
    unsupportedFile: 'Unsupported file type. Please upload PNG, JPG, MP4, or MOV files.',
    voiceNotSupported: 'Voice input not supported in this browser. Try Chrome or Edge.',
    noSpeechDetected: 'No speech detected. Please try again.',
    micPermissionDenied: 'Microphone permission denied.',
    voiceInputError: 'Voice input error. Please try again.',
    voiceOutputError: 'Voice output error. Please try again.',
    recordingStarted: 'Recording started. Speak now...',
    recordingStopped: 'Recording stopped',
    readingAloud: 'Reading aloud...',
    readingStopped: 'Reading stopped',
    stopReading: 'Stop Reading',
  },
  hi: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'अभी जांचें',
    newAnalysis: 'नई जांच',
    
    // Home Page
    heroLabel: 'उन्नत AI फोरेंसिक',
    heroTitle: 'AI सामग्री और धोखाधड़ी का पता लगाएं',
    heroDescription: 'VeriSure AI-निर्मित सामग्री की पहचान करने और घोटाले के जोखिम का आकलन करने के लिए फोरेंसिक-ग्रेड विश्लेषण प्रदान करता है। भारतीयों को लक्षित करने वाले डीपफेक, हेरफेर की गई मीडिया और सोशल इंजीनियरिंग हमलों से खुद को बचाएं।',
    getStarted: 'शुरू करें',
    howItWorks: 'यह कैसे काम करता है',
    safe: 'सुरक्षित',
    warning: 'चेतावनी',
    danger: 'खतरा',
    
    // Analysis Page
    forensicAnalysis: 'फोरेंसिक विश्लेषण',
    submitContent: 'विश्लेषण के लिए सामग्री जमा करें',
    submitDescription: 'फ़ाइलें अपलोड करें, टेक्स्ट पेस्ट करें, या URL प्रदान करें। VeriSure AI मूल और घोटाले के संकेतकों के लिए विश्लेषण करेगा।',
    upload: 'अपलोड',
    text: 'टेक्स्ट',
    url: 'URL',
    clickToUpload: 'अपलोड करने के लिए क्लिक करें या ड्रैग करें',
    fileTypes: 'PNG, JPG, MP4, MOV (अधिकतम 50MB)',
    pasteText: 'यहां संदिग्ध टेक्स्ट, संदेश या सामग्री पेस्ट करें...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'विश्लेषण के लिए एक छवि, वीडियो या वेबपेज की ओर इशारा करते हुए URL दर्ज करें',
    cancel: 'रद्द करें',
    analyze: 'अभी जांचें',
    analyzing: 'जांच हो रही है...',
    recordVoice: 'आवाज रिकॉर्ड करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    listening: 'सुन रहा हूं...',
    
    // Results Page
    analysisReport: 'विश्लेषण रिपोर्ट',
    forensicComplete: 'फोरेंसिक विश्लेषण पूर्ण',
    highRisk: 'उच्च जोखिम - संभावित घोटाला',
    highRiskWarning: 'जवाब न दें या कोई जानकारी साझा न करें!',
    mediumRisk: 'मध्यम जोखिम - सावधान रहें',
    lowRisk: 'कम जोखिम - सुरक्षित दिखता है',
    originClassification: 'मूल वर्गीकरण',
    confidence: 'विश्वास',
    indicators: 'संकेतक',
    scamRisk: 'घोटाले का जोखिम स्तर',
    patternsDetected: 'पैटर्न का पता चला',
    evidenceSummary: 'साक्ष्य सारांश',
    signalsDetected: 'संकेत का पता चला',
    forensicNotes: 'फोरेंसिक नोट्स',
    reportDetails: 'रिपोर्ट विवरण',
    reportId: 'रिपोर्ट ID',
    timestamp: 'समय टिकट',
    contentHash: 'सामग्री हैश (SHA-256)',
    recommendedActions: 'अनुशंसित कार्रवाई',
    analysisSummary: 'विश्लेषण सारांश',
    limitations: 'सीमाएं',
    readAloud: 'ज़ोर से पढ़ें',
    shareWhatsApp: 'WhatsApp पर शेयर करें',
    
    // Risk Levels
    highRiskLabel: 'उच्च जोखिम',
    mediumRiskLabel: 'मध्यम जोखिम',
    lowRiskLabel: 'कम जोखिम',
    
    // Toast Messages
    fileSelected: 'फ़ाइल चुनी गई',
    selectFile: 'कृपया अपलोड करने के लिए एक फ़ाइल चुनें',
    enterText: 'कृपया विश्लेषण के लिए टेक्स्ट दर्ज करें',
    enterUrlText: 'कृपया विश्लेषण के लिए URL दर्ज करें',
    analysisComplete: 'विश्लेषण पूर्ण!',
    analysisFailed: 'विश्लेषण विफल। कृपया पुनः प्रयास करें।',
    unsupportedFile: 'असमर्थित फ़ाइल प्रकार। कृपया PNG, JPG, MP4, या MOV फ़ाइलें अपलोड करें।',
    voiceNotSupported: 'इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है। Chrome या Edge आज़माएं।',
    noSpeechDetected: 'कोई भाषण नहीं मिला। कृपया पुनः प्रयास करें।',
    micPermissionDenied: 'माइक्रोफोन अनुमति अस्वीकृत।',
    voiceInputError: 'वॉयस इनपुट त्रुटि। कृपया पुनः प्रयास करें।',
    voiceOutputError: 'वॉयस आउटपुट त्रुटि। कृपया पुनः प्रयास करें।',
    recordingStarted: 'रिकॉर्डिंग शुरू हुई। अब बोलें...',
    recordingStopped: 'रिकॉर्डिंग बंद हुई',
    readingAloud: 'ज़ोर से पढ़ रहा है...',
    readingStopped: 'पढ़ना बंद हुआ',
    stopReading: 'पढ़ना बंद करें',
  },
  ta: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'இப்போது பகுப்பாய்வு செய்க',
    newAnalysis: 'புதிய பகுப்பாய்வு',
    
    // Home Page
    heroLabel: 'மேம்பட்ட AI தடயவியல்',
    heroTitle: 'AI உள்ளடக்கம் மற்றும் மோசடி அச்சுறுத்தல்களைக் கண்டறியவும்',
    heroDescription: 'VeriSure AI-உருவாக்கிய உள்ளடக்கத்தை அடையாளம் காணவும் மோசடி அபாயத்தை மதிப்பிடவும் தடயவியல்-தர பகுப்பாய்வை வழங்குகிறது.',
    getStarted: 'தொடங்குங்கள்',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    safe: 'பாதுகாப்பானது',
    warning: 'எச்சரிக்கை',
    danger: 'ஆபத்து',
    
    // Analysis Page
    forensicAnalysis: 'தடயவியல் பகுப்பாய்வு',
    submitContent: 'பகுப்பாய்வுக்காக உள்ளடக்கத்தைச் சமர்ப்பிக்கவும்',
    submitDescription: 'கோப்புகளை பதிவேற்றவும், உரையை ஒட்டவும் அல்லது URL களை வழங்கவும்.',
    upload: 'பதிவேற்றம்',
    text: 'உரை',
    url: 'URL',
    clickToUpload: 'பதிவேற்ற கிளிக் செய்க',
    fileTypes: 'PNG, JPG, MP4, MOV (அதிகபட்சம் 50MB)',
    pasteText: 'சந்தேகத்திற்குரிய உரை, செய்திகள் அல்லது உள்ளடக்கத்தை இங்கே ஒட்டவும்...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'பகுப்பாய்வுக்கான படம், வீடியோ அல்லது வலைப்பக்கத்தை குறிக்கும் URL ஐ உள்ளிடவும்',
    cancel: 'ரத்துசெய்',
    analyze: 'இப்போது பகுப்பாய்வு செய்க',
    analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
    recordVoice: 'குரலை பதிவுசெய்க',
    stopRecording: 'பதிவை நிறுத்து',
    listening: 'கேட்கிறது...',
    
    // Results Page
    analysisReport: 'பகுப்பாய்வு அறிக்கை',
    forensicComplete: 'தடயவியல் பகுப்பாய்வு முழுமை',
    highRisk: 'உயர் ஆபத்து - மோசடி சாத்தியம்',
    highRiskWarning: 'பதிலளிக்காதீர்கள் அல்லது எந்த தகவலையும் பகிர்ந்து கொள்ளாதீர்கள்!',
    mediumRisk: 'மிதமான ஆபத்து - கவனமாக இருங்கள்',
    lowRisk: 'குறைந்த ஆபத்து - பாதுகாப்பாக தெரிகிறது',
    originClassification: 'தோற்ற வகைப்பாடு',
    confidence: 'நம்பிக்கை',
    indicators: 'குறிகாட்டிகள்',
    scamRisk: 'மோசடி ஆபத்து நிலை',
    patternsDetected: 'வடிவங்கள் கண்டறியப்பட்டன',
    evidenceSummary: 'சான்று சுருக்கம்',
    signalsDetected: 'சமிக்ஞைகள் கண்டறியப்பட்டன',
    forensicNotes: 'தடயவியல் குறிப்புகள்',
    reportDetails: 'அறிக்கை விவரங்கள்',
    reportId: 'அறிக்கை ID',
    timestamp: 'நேர முத்திரை',
    contentHash: 'உள்ளடக்க ஹாஷ் (SHA-256)',
    recommendedActions: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்',
    analysisSummary: 'பகுப்பாய்வு சுருக்கம்',
    limitations: 'வரம்புகள்',
    readAloud: 'உரக்கப் படிக்கவும்',
    shareWhatsApp: 'WhatsApp இல் பகிரவும்',
    
    // Risk Levels
    highRiskLabel: 'உயர் ஆபத்து',
    mediumRiskLabel: 'மிதமான ஆபத்து',
    lowRiskLabel: 'குறைந்த ஆபத்து',
    
    // Toast Messages
    fileSelected: 'கோப்பு தேர்ந்தெடுக்கப்பட்டது',
    selectFile: 'பதிவேற்ற ஒரு கோப்பைத் தேர்ந்தெடுக்கவும்',
    enterText: 'பகுப்பாய்வுக்கான உரையை உள்ளிடவும்',
    enterUrlText: 'பகுப்பாய்வுக்கான URL ஐ உள்ளிடவும்',
    analysisComplete: 'பகுப்பாய்வு முழுமை!',
    analysisFailed: 'பகுப்பாய்வு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    unsupportedFile: 'ஆதரிக்கப்படாத கோப்பு வகை. PNG, JPG, MP4 அல்லது MOV கோப்புகளை பதிவேற்றவும்.',
    voiceNotSupported: 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை. Chrome அல்லது Edge ஐப் பயன்படுத்தவும்.',
    noSpeechDetected: 'எந்த பேச்சும் கண்டறியப்படவில்லை. மீண்டும் முயற்சிக்கவும்.',
    micPermissionDenied: 'மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது.',
    voiceInputError: 'குரல் உள்ளீட்டு பிழை. மீண்டும் முயற்சிக்கவும்.',
    voiceOutputError: 'குரல் வெளியீட்டு பிழை. மீண்டும் முயற்சிக்கவும்.',
    recordingStarted: 'பதிவு தொடங்கியது. இப்போது பேசுங்கள்...',
    recordingStopped: 'பதிவு நிறுத்தப்பட்டது',
    readingAloud: 'உரக்க வாசிக்கிறது...',
    readingStopped: 'வாசிப்பு நிறுத்தப்பட்டது',
    stopReading: 'வாசிப்பை நிறுத்து',
  },
  bn: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'এখনই বিশ্লেষণ করুন',
    newAnalysis: 'নতুন বিশ্লেষণ',
    
    // Home Page
    heroLabel: 'উন্নত AI ফরেনসিক',
    heroTitle: 'AI কন্টেন্ট এবং স্ক্যাম হুমকি সনাক্ত করুন',
    heroDescription: 'VeriSure AI-উৎপন্ন বিষয়বস্তু সনাক্ত করতে এবং স্ক্যাম ঝুঁকি মূল্যায়ন করতে ফরেনসিক-গ্রেড বিশ্লেষণ প্রদান করে।',
    getStarted: 'শুরু করুন',
    howItWorks: 'এটি কীভাবে কাজ করে',
    safe: 'নিরাপদ',
    warning: 'সতর্কতা',
    danger: 'বিপদ',
    
    // Analysis Page
    forensicAnalysis: 'ফরেনসিক বিশ্লেষণ',
    submitContent: 'বিশ্লেষণের জন্য বিষয়বস্তু জমা দিন',
    submitDescription: 'ফাইল আপলোড করুন, টেক্সট পেস্ট করুন বা URL প্রদান করুন।',
    upload: 'আপলোড',
    text: 'পাঠ্য',
    url: 'URL',
    clickToUpload: 'আপলোড করতে ক্লিক করুন',
    fileTypes: 'PNG, JPG, MP4, MOV (সর্বোচ্চ 50MB)',
    pasteText: 'এখানে সন্দেহজনক টেক্সট, বার্তা বা বিষয়বস্তু পেস্ট করুন...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'বিশ্লেষণের জন্য একটি ছবি, ভিডিও বা ওয়েবপেজ নির্দেশ করে এমন URL লিখুন',
    cancel: 'বাতিল করুন',
    analyze: 'এখনই বিশ্লেষণ করুন',
    analyzing: 'বিশ্লেষণ করা হচ্ছে...',
    recordVoice: 'ভয়েস রেকর্ড করুন',
    stopRecording: 'রেকর্ডিং বন্ধ করুন',
    listening: 'শুনছি...',
    
    // Results Page
    analysisReport: 'বিশ্লেষণ রিপোর্ট',
    forensicComplete: 'ফরেনসিক বিশ্লেষণ সম্পূর্ণ',
    highRisk: 'উচ্চ ঝুঁকি - সম্ভাব্য স্ক্যাম',
    highRiskWarning: 'জবাব দেবেন না বা কোনো তথ্য শেয়ার করবেন না!',
    mediumRisk: 'মাঝারি ঝুঁকি - সতর্ক থাকুন',
    lowRisk: 'কম ঝুঁকি - নিরাপদ মনে হচ্ছে',
    originClassification: 'উৎপত্তি শ্রেণীবিভাগ',
    confidence: 'আত্মবিশ্বাস',
    indicators: 'সূচক',
    scamRisk: 'স্ক্যাম ঝুঁকি স্তর',
    patternsDetected: 'প্যাটার্ন সনাক্ত করা হয়েছে',
    evidenceSummary: 'প্রমাণ সারাংশ',
    signalsDetected: 'সংকেত সনাক্ত করা হয়েছে',
    forensicNotes: 'ফরেনসিক নোট',
    reportDetails: 'রিপোর্ট বিবরণ',
    reportId: 'রিপোর্ট ID',
    timestamp: 'টাইমস্ট্যাম্প',
    contentHash: 'কন্টেন্ট হ্যাশ (SHA-256)',
    recommendedActions: 'প্রস্তাবিত পদক্ষেপ',
    analysisSummary: 'বিশ্লেষণ সারাংশ',
    limitations: 'সীমাবদ্ধতা',
    readAloud: 'জোরে পড়ুন',
    shareWhatsApp: 'WhatsApp এ শেয়ার করুন',
    stopReading: 'পড়া বন্ধ করুন',
    
    // Risk Levels
    highRiskLabel: 'উচ্চ ঝুঁকি',
    mediumRiskLabel: 'মাঝারি ঝুঁকি',
    lowRiskLabel: 'কম ঝুঁকি',
    
    // Toast Messages
    fileSelected: 'ফাইল নির্বাচিত',
    selectFile: 'আপলোড করার জন্য একটি ফাইল নির্বাচন করুন',
    enterText: 'বিশ্লেষণের জন্য টেক্সট লিখুন',
    enterUrlText: 'বিশ্লেষণের জন্য URL লিখুন',
    analysisComplete: 'বিশ্লেষণ সম্পূর্ণ!',
    analysisFailed: 'বিশ্লেষণ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    unsupportedFile: 'অসমর্থিত ফাইল প্রকার। PNG, JPG, MP4, বা MOV ফাইল আপলোড করুন।',
    voiceNotSupported: 'এই ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়। Chrome বা Edge ব্যবহার করুন।',
    noSpeechDetected: 'কোনো বক্তৃতা সনাক্ত করা হয়নি। আবার চেষ্টা করুন।',
    micPermissionDenied: 'মাইক্রোফোন অনুমতি প্রত্যাখ্যান করা হয়েছে।',
    voiceInputError: 'ভয়েস ইনপুট ত্রুটি। আবার চেষ্টা করুন।',
    voiceOutputError: 'ভয়েস আউটপুট ত্রুটি। আবার চেষ্টা করুন।',
    recordingStarted: 'রেকর্ডিং শুরু হয়েছে। এখন বলুন...',
    recordingStopped: 'রেকর্ডিং বন্ধ হয়েছে',
    readingAloud: 'জোরে পড়া হচ্ছে...',
    readingStopped: 'পড়া বন্ধ হয়েছে',
  },
  mr: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'आता विश्लेषण करा',
    newAnalysis: 'नवीन विश्लेषण',
    
    // Home Page
    heroLabel: 'प्रगत AI फॉरेन्सिक',
    heroTitle: 'AI सामग्री आणि घोटाळा शोधा',
    heroDescription: 'VeriSure AI-निर्मित सामग्री ओळखण्यासाठी आणि घोटाळा जोखीम मूल्यांकनासाठी फॉरेन्सिक-ग्रेड विश्लेषण प्रदान करते।',
    getStarted: 'सुरू करा',
    howItWorks: 'हे कसे कार्य करते',
    safe: 'सुरक्षित',
    warning: 'चेतावणी',
    danger: 'धोका',
    
    // Analysis Page
    forensicAnalysis: 'फॉरेन्सिक विश्लेषण',
    submitContent: 'विश्लेषणासाठी सामग्री सबमिट करा',
    submitDescription: 'फाइल अपलोड करा, मजकूर पेस्ट करा किंवा URL प्रदान करा।',
    upload: 'अपलोड',
    text: 'मजकूर',
    url: 'URL',
    clickToUpload: 'अपलोड करण्यासाठी क्लिक करा',
    fileTypes: 'PNG, JPG, MP4, MOV (कमाल 50MB)',
    pasteText: 'येथे संशयास्पद मजकूर, संदेश किंवा सामग्री पेस्ट करा...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'विश्लेषणासाठी प्रतिमा, व्हिडिओ किंवा वेबपेज दर्शविणारा URL प्रविष्ट करा',
    cancel: 'रद्द करा',
    analyze: 'आता विश्लेषण करा',
    analyzing: 'विश्लेषण करत आहे...',
    recordVoice: 'आवाज रेकॉर्ड करा',
    stopRecording: 'रेकॉर्डिंग थांबवा',
    listening: 'ऐकत आहे...',
    
    // Results Page
    analysisReport: 'विश्लेषण अहवाल',
    forensicComplete: 'फॉरेन्सिक विश्लेषण पूर्ण',
    highRisk: 'उच्च धोका - संभाव्य घोटाळा',
    highRiskWarning: 'उत्तर देऊ नका किंवा कोणतीही माहिती शेअर करू नका!',
    mediumRisk: 'मध्यम धोका - सावध रहा',
    lowRisk: 'कमी धोका - सुरक्षित दिसते',
    originClassification: 'मूळ वर्गीकरण',
    confidence: 'विश्वास',
    indicators: 'निर्देशक',
    scamRisk: 'घोटाळा धोका पातळी',
    patternsDetected: 'पॅटर्न आढळले',
    evidenceSummary: 'पुरावा सारांश',
    signalsDetected: 'सिग्नल आढळले',
    forensicNotes: 'फॉरेन्सिक नोट्स',
    reportDetails: 'अहवाल तपशील',
    reportId: 'अहवाल ID',
    timestamp: 'टाइमस्टॅम्प',
    contentHash: 'सामग्री हॅश (SHA-256)',
    recommendedActions: 'शिफारस केलेल्या कृती',
    analysisSummary: 'विश्लेषण सारांश',
    limitations: 'मर्यादा',
    readAloud: 'मोठ्याने वाचा',
    shareWhatsApp: 'WhatsApp वर शेअर करा',
    stopReading: 'वाचणे थांबवा',
    
    // Risk Levels
    highRiskLabel: 'उच्च धोका',
    mediumRiskLabel: 'मध्यम धोका',
    lowRiskLabel: 'कमी धोका',
    
    // Toast Messages
    fileSelected: 'फाइल निवडली',
    selectFile: 'अपलोड करण्यासाठी फाइल निवडा',
    enterText: 'विश्लेषणासाठी मजकूर प्रविष्ट करा',
    enterUrlText: 'विश्लेषणासाठी URL प्रविष्ट करा',
    analysisComplete: 'विश्लेषण पूर्ण!',
    analysisFailed: 'विश्लेषण अयशस्वी. कृपया पुन्हा प्रयत्न करा।',
    unsupportedFile: 'असमर्थित फाइल प्रकार। PNG, JPG, MP4, किंवा MOV फाइल अपलोड करा।',
    voiceNotSupported: 'या ब्राउझरमध्ये आवाज इनपुट समर्थित नाही। Chrome किंवा Edge वापरा।',
    noSpeechDetected: 'कोणतेही भाषण आढळले नाही। कृपया पुन्हा प्रयत्न करा।',
    micPermissionDenied: 'मायक्रोफोन परवानगी नाकारली गेली.',
    voiceInputError: 'आवाज इनपुट त्रुटी. कृपया पुन्हा प्रयत्न करा।',
    voiceOutputError: 'आवाज आउटपुट त्रुटी. कृपया पुन्हा प्रयत्न करा।',
    recordingStarted: 'रेकॉर्डिंग सुरू झाले. आता बोला...',
    recordingStopped: 'रेकॉर्डिंग थांबले',
    readingAloud: 'मोठ्याने वाचत आहे...',
    readingStopped: 'वाचणे थांबले',
  },
  te: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'ఇప్పుడే విశ్లేషించండి',
    newAnalysis: 'కొత్త విశ్లేషణ',
    
    // Home Page
    heroLabel: 'అధునాతన AI ఫోరెన్సిక్',
    heroTitle: 'AI కంటెంట్ మరియు స్కామ్ను గుర్తించండి',
    heroDescription: 'VeriSure AI-ఉత్పత్తి చేసిన కంటెంట్‌ను గుర్తించడానికి మరియు స్కామ్ ప్రమాదాన్ని అంచనా వేయడానికి ఫోరెన్సిక్-గ్రేడ్ విశ్లేషణను అందిస్తుంది.',
    getStarted: 'ప్రారంభించండి',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    safe: 'సురక్షితం',
    warning: 'హెచ్చరిక',
    danger: 'ప్రమాదం',
    
    // Analysis Page
    forensicAnalysis: 'ఫోరెన్సిక్ విశ్లేషణ',
    submitContent: 'విశ్లేషణ కోసం కంటెంట్ సమర్పించండి',
    submitDescription: 'ఫైల్‌లను అప్‌లోడ్ చేయండి, టెక్స్ట్ పేస్ట్ చేయండి లేదా URL అందించండి.',
    upload: 'అప్‌లోడ్',
    text: 'వచనం',
    url: 'URL',
    clickToUpload: 'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    fileTypes: 'PNG, JPG, MP4, MOV (గరిష్టంగా 50MB)',
    pasteText: 'ఇక్కడ అనుమానాస్పద టెక్స్ట్, సందేశాలు లేదా కంటెంట్‌ను పేస్ట్ చేయండి...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'విశ్లేషణ కోసం చిత్రం, వీడియో లేదా వెబ్‌పేజీని సూచించే URL ను నమోదు చేయండి',
    cancel: 'రద్దు చేయండి',
    analyze: 'ఇప్పుడే విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది...',
    recordVoice: 'వాయిస్ రికార్డ్ చేయండి',
    stopRecording: 'రికార్డింగ్ ఆపండి',
    listening: 'వింటోంది...',
    
    // Results Page
    analysisReport: 'విశ్లేషణ నివేదిక',
    forensicComplete: 'ఫోరెన్సిక్ విశ్లేషణ పూర్తయింది',
    highRisk: 'అధిక ప్రమాదం - స్కామ్ అవకాశం',
    highRiskWarning: 'స్పందించవద్దు లేదా ఎలాంటి సమాచారాన్ని పంచుకోవద్దు!',
    mediumRisk: 'మధ్యస్థ ప్రమాదం - జాగ్రత్తగా ఉండండి',
    lowRisk: 'తక్కువ ప్రమాదం - సురక్షితంగా కనిపిస్తుంది',
    originClassification: 'మూల వర్గీకరణ',
    confidence: 'విశ్వాసం',
    indicators: 'సూచికలు',
    scamRisk: 'స్కామ్ ప్రమాద స్థాయి',
    patternsDetected: 'నమూనాలు గుర్తించబడ్డాయి',
    evidenceSummary: 'సాక్ష్యాల సారాంశం',
    signalsDetected: 'సంకేతాలు గుర్తించబడ్డాయి',
    forensicNotes: 'ఫోరెన్సిక్ నోట్స్',
    reportDetails: 'నివేదిక వివరాలు',
    reportId: 'నివేదిక ID',
    timestamp: 'టైమ్‌స్టాంప్',
    contentHash: 'కంటెంట్ హాష్ (SHA-256)',
    recommendedActions: 'సిఫార్సు చేయబడిన చర్యలు',
    analysisSummary: 'విశ్లేషణ సారాంశం',
    limitations: 'పరిమితులు',
    readAloud: 'బిగ్గరగా చదవండి',
    shareWhatsApp: 'WhatsApp లో భాగస్వామ్యం చేయండి',
    stopReading: 'చదవడం ఆపండి',
    
    // Risk Levels
    highRiskLabel: 'అధిక ప్రమాదం',
    mediumRiskLabel: 'మధ్యస్థ ప్రమాదం',
    lowRiskLabel: 'తక్కువ ప్రమాదం',
    
    // Toast Messages
    fileSelected: 'ఫైల్ ఎంచుకోబడింది',
    selectFile: 'అప్‌లోడ్ చేయడానికి ఫైల్‌ను ఎంచుకోండి',
    enterText: 'విశ్లేషణ కోసం టెక్స్ట్ నమోదు చేయండి',
    enterUrlText: 'విశ్లేషణ కోసం URL నమోదు చేయండి',
    analysisComplete: 'విశ్లేషణ పూర్తయింది!',
    analysisFailed: 'విశ్లేషణ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    unsupportedFile: 'మద్దతు లేని ఫైల్ రకం. PNG, JPG, MP4, లేదా MOV ఫైల్‌లను అప్‌లోడ్ చేయండి.',
    voiceNotSupported: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ మద్దతు లేదు. Chrome లేదా Edge ఉపయోగించండి.',
    noSpeechDetected: 'ప్రసంగం గుర్తించబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    micPermissionDenied: 'మైక్రోఫోన్ అనుమతి తిరస్కరించబడింది.',
    voiceInputError: 'వాయిస్ ఇన్‌పుట్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.',
    voiceOutputError: 'వాయిస్ అవుట్‌పుట్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.',
    recordingStarted: 'రికార్డింగ్ ప్రారంభమైంది. ఇప్పుడు మాట్లాడండి...',
    recordingStopped: 'రికార్డింగ్ ఆగిపోయింది',
    readingAloud: 'బిగ్గరగా చదువుతోంది...',
    readingStopped: 'చదవడం ఆగిపోయింది',
  },
  gu: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'હમણાં વિશ્લેષણ કરો',
    newAnalysis: 'નવું વિશ્લેષણ',
    
    // Home Page
    heroLabel: 'અદ્યતન AI ફોરેન્સિક',
    heroTitle: 'AI સામગ્રી અને સ્કેમ શોધો',
    heroDescription: 'VeriSure AI-જનરેટેડ સામગ્રીને ઓળખવા અને સ્કેમ જોખમનું મૂલ્યાંકન કરવા માટે ફોરેન્સિક-ગ્રેડ વિશ્લેષણ પ્રદાન કરે છે.',
    getStarted: 'શરૂ કરો',
    howItWorks: 'આ કેવી રીતે કામ કરે છે',
    safe: 'સુરક્ષિત',
    warning: 'ચેતવણી',
    danger: 'ખતરો',
    
    // Analysis Page
    forensicAnalysis: 'ફોરેન્સિક વિશ્લેષણ',
    submitContent: 'વિશ્લેષણ માટે સામગ્રી સબમિટ કરો',
    submitDescription: 'ફાઇલો અપલોડ કરો, ટેક્સ્ટ પેસ્ટ કરો અથવા URL પ્રદાન કરો.',
    upload: 'અપલોડ',
    text: 'ટેક્સ્ટ',
    url: 'URL',
    clickToUpload: 'અપલોડ કરવા ક્લિક કરો',
    fileTypes: 'PNG, JPG, MP4, MOV (મહત્તમ 50MB)',
    pasteText: 'અહીં શંકાસ્પદ ટેક્સ્ટ, સંદેશાઓ અથવા સામગ્રી પેસ્ટ કરો...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'વિશ્લેષણ માટે છબી, વિડિઓ અથવા વેબપેજ તરફ નિર્દેશ કરતું URL દાખલ કરો',
    cancel: 'રદ કરો',
    analyze: 'હમણાં વિશ્લેષણ કરો',
    analyzing: 'વિશ્લેષણ કરી રહ્યું છે...',
    recordVoice: 'અવાજ રેકોર્ડ કરો',
    stopRecording: 'રેકોર્ડિંગ બંધ કરો',
    listening: 'સાંભળી રહ્યું છે...',
    
    // Results Page
    analysisReport: 'વિશ્લેષણ રિપોર્ટ',
    forensicComplete: 'ફોરેન્સિક વિશ્લેષણ પૂર્ણ',
    highRisk: 'ઊંચું જોખમ - સંભવિત સ્કેમ',
    highRiskWarning: 'જવાબ આપશો નહીં અથવા કોઈ માહિતી શેર કરશો નહીં!',
    mediumRisk: 'મધ્યમ જોખમ - સાવચેત રહો',
    lowRisk: 'ઓછું જોખમ - સુરક્ષિત લાગે છે',
    originClassification: 'મૂળ વર્ગીકરણ',
    confidence: 'આત્મવિશ્વાસ',
    indicators: 'સૂચકો',
    scamRisk: 'સ્કેમ જોખમ સ્તર',
    patternsDetected: 'પેટર્ન શોધાયા',
    evidenceSummary: 'પુરાવા સારાંશ',
    signalsDetected: 'સિગ્નલ શોધાયા',
    forensicNotes: 'ફોરેન્સિક નોંધો',
    reportDetails: 'રિપોર્ટ વિગતો',
    reportId: 'રિપોર્ટ ID',
    timestamp: 'ટાઇમસ્ટેમ્પ',
    contentHash: 'સામગ્રી હેશ (SHA-256)',
    recommendedActions: 'ભલામણ કરેલ ક્રિયાઓ',
    analysisSummary: 'વિશ્લેષણ સારાંશ',
    limitations: 'મર્યાદાઓ',
    readAloud: 'મોટેથી વાંચો',
    shareWhatsApp: 'WhatsApp પર શેર કરો',
    stopReading: 'વાંચવાનું બંધ કરો',
    
    // Risk Levels
    highRiskLabel: 'ઊંચું જોખમ',
    mediumRiskLabel: 'મધ્યમ જોખમ',
    lowRiskLabel: 'ઓછું જોખમ',
    
    // Toast Messages
    fileSelected: 'ફાઇલ પસંદ કરી',
    selectFile: 'અપલોડ કરવા માટે ફાઇલ પસંદ કરો',
    enterText: 'વિશ્લેષણ માટે ટેક્સ્ટ દાખલ કરો',
    enterUrlText: 'વિશ્લેષણ માટે URL દાખલ કરો',
    analysisComplete: 'વિશ્લેષણ પૂર્ણ!',
    analysisFailed: 'વિશ્લેષણ નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    unsupportedFile: 'અસમર્થિત ફાઇલ પ્રકાર. PNG, JPG, MP4, અથવા MOV ફાઇલો અપલોડ કરો.',
    voiceNotSupported: 'આ બ્રાઉઝરમાં અવાજ ઇનપુટ સમર્થિત નથી. Chrome અથવા Edge વાપરો.',
    noSpeechDetected: 'કોઈ ભાષણ શોધાયું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
    micPermissionDenied: 'માઇક્રોફોન પરવાનગી નકારવામાં આવી.',
    voiceInputError: 'અવાજ ઇનપુટ ભૂલ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    voiceOutputError: 'અવાજ આઉટપુટ ભૂલ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    recordingStarted: 'રેકોર્ડિંગ શરૂ થયું. હવે બોલો...',
    recordingStopped: 'રેકોર્ડિંગ બંધ થયું',
    readingAloud: 'મોટેથી વાંચી રહ્યું છે...',
    readingStopped: 'વાંચવાનું બંધ થયું',
  },
  kn: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'ಈಗ ವಿಶ್ಲೇಷಿಸಿ',
    newAnalysis: 'ಹೊಸ ವಿಶ್ಲೇಷಣೆ',
    
    // Home Page
    heroLabel: 'ಮುಂದುವರಿದ AI ಫೊರೆನ್ಸಿಕ್',
    heroTitle: 'AI ವಿಷಯ ಮತ್ತು ಸ್ಕ್ಯಾಮ್ ಪತ್ತೆಹಚ್ಚಿ',
    heroDescription: 'VeriSure AI-ಉತ್ಪತ್ತಿಯಾದ ವಿಷಯವನ್ನು ಗುರುತಿಸಲು ಮತ್ತು ಸ್ಕ್ಯಾಮ್ ಅಪಾಯವನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಫೊರೆನ್ಸಿಕ್-ಗ್ರೇಡ್ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಒದಗಿಸುತ್ತದೆ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    safe: 'ಸುರಕ್ಷಿತ',
    warning: 'ಎಚ್ಚರಿಕೆ',
    danger: 'ಅಪಾಯ',
    
    // Analysis Page
    forensicAnalysis: 'ಫೊರೆನ್ಸಿಕ್ ವಿಶ್ಲೇಷಣೆ',
    submitContent: 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ವಿಷಯವನ್ನು ಸಲ್ಲಿಸಿ',
    submitDescription: 'ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ಪಠ್ಯವನ್ನು ಅಂಟಿಸಿ ಅಥವಾ URL ಒದಗಿಸಿ.',
    upload: 'ಅಪ್‌ಲೋಡ್',
    text: 'ಪಠ್ಯ',
    url: 'URL',
    clickToUpload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    fileTypes: 'PNG, JPG, MP4, MOV (ಗರಿಷ್ಠ 50MB)',
    pasteText: 'ಇಲ್ಲಿ ಸಂಶಯಾಸ್ಪದ ಪಠ್ಯ, ಸಂದೇಶಗಳು ಅಥವಾ ವಿಷಯವನ್ನು ಅಂಟಿಸಿ...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಚಿತ್ರ, ವೀಡಿಯೋ ಅಥವಾ ವೆಬ್‌ಪುಟವನ್ನು ಸೂಚಿಸುವ URL ನಮೂದಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    analyze: 'ಈಗ ವಿಶ್ಲೇಷಿಸಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    recordVoice: 'ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಮಾಡಿ',
    stopRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    
    // Results Page
    analysisReport: 'ವಿಶ್ಲೇಷಣೆ ವರದಿ',
    forensicComplete: 'ಫೊರೆನ್ಸಿಕ್ ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
    highRisk: 'ಹೆಚ್ಚಿನ ಅಪಾಯ - ಸಂಭವನೀಯ ಸ್ಕ್ಯಾಮ್',
    highRiskWarning: 'ಪ್ರತಿಕ್ರಿಯಿಸಬೇಡಿ ಅಥವಾ ಯಾವುದೇ ಮಾಹಿತಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳಬೇಡಿ!',
    mediumRisk: 'ಮಧ್ಯಮ ಅಪಾಯ - ಜಾಗರೂಕರಾಗಿರಿ',
    lowRisk: 'ಕಡಿಮೆ ಅಪಾಯ - ಸುರಕ್ಷಿತವಾಗಿ ಕಾಣುತ್ತದೆ',
    originClassification: 'ಮೂಲ ವರ್ಗೀಕರಣ',
    confidence: 'ವಿಶ್ವಾಸ',
    indicators: 'ಸೂಚಕಗಳು',
    scamRisk: 'ಸ್ಕ್ಯಾಮ್ ಅಪಾಯ ಮಟ್ಟ',
    patternsDetected: 'ಮಾದರಿಗಳು ಪತ್ತೆಯಾಗಿವೆ',
    evidenceSummary: 'ಸಾಕ್ಷ್ಯ ಸಾರಾಂಶ',
    signalsDetected: 'ಸಂಕೇತಗಳು ಪತ್ತೆಯಾಗಿವೆ',
    forensicNotes: 'ಫೊರೆನ್ಸಿಕ್ ಟಿಪ್ಪಣಿಗಳು',
    reportDetails: 'ವರದಿ ವಿವರಗಳು',
    reportId: 'ವರದಿ ID',
    timestamp: 'ಟೈಮ್‌ಸ್ಟ್ಯಾಂಪ್',
    contentHash: 'ವಿಷಯ ಹ್ಯಾಶ್ (SHA-256)',
    recommendedActions: 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಕ್ರಮಗಳು',
    analysisSummary: 'ವಿಶ್ಲೇಷಣೆ ಸಾರಾಂಶ',
    limitations: 'ಮಿತಿಗಳು',
    readAloud: 'ಜೋರಾಗಿ ಓದಿ',
    shareWhatsApp: 'WhatsApp ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    stopReading: 'ಓದುವುದನ್ನು ನಿಲ್ಲಿಸಿ',
    
    // Risk Levels
    highRiskLabel: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    mediumRiskLabel: 'ಮಧ್ಯಮ ಅಪಾಯ',
    lowRiskLabel: 'ಕಡಿಮೆ ಅಪಾಯ',
    
    // Toast Messages
    fileSelected: 'ಫೈಲ್ ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    selectFile: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
    enterText: 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ',
    enterUrlText: 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ URL ನಮೂದಿಸಿ',
    analysisComplete: 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    analysisFailed: 'ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    unsupportedFile: 'ಬೆಂಬಲಿಸದ ಫೈಲ್ ಪ್ರಕಾರ. PNG, JPG, MP4, ಅಥವಾ MOV ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    voiceNotSupported: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ. Chrome ಅಥವಾ Edge ಬಳಸಿ.',
    noSpeechDetected: 'ಯಾವುದೇ ಭಾಷಣ ಪತ್ತೆಯಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    micPermissionDenied: 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ.',
    voiceInputError: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    voiceOutputError: 'ಧ್ವನಿ ಔಟ್‌ಪುಟ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    recordingStarted: 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭವಾಗಿದೆ. ಈಗ ಮಾತನಾಡಿ...',
    recordingStopped: 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಲಾಗಿದೆ',
    readingAloud: 'ಜೋರಾಗಿ ಓದುತ್ತಿದೆ...',
    readingStopped: 'ಓದುವುದನ್ನು ನಿಲ್ಲಿಸಲಾಗಿದೆ',
  },
  ml: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'ഇപ്പോൾ വിശകലനം ചെയ്യുക',
    newAnalysis: 'പുതിയ വിശകലനം',
    
    // Home Page
    heroLabel: 'വിപുലമായ AI ഫോറൻസിക്',
    heroTitle: 'AI ഉള്ളടക്കവും തട്ടിപ്പും കണ്ടെത്തുക',
    heroDescription: 'VeriSure AI-സൃഷ്ടിച്ച ഉള്ളടക്കം തിരിച്ചറിയുന്നതിനും തട്ടിപ്പ് അപകടസാധ്യത വിലയിരുത്തുന്നതിനും ഫോറൻസിക്-ഗ്രേഡ് വിശകലനം നൽകുന്നു.',
    getStarted: 'ആരംഭിക്കുക',
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    safe: 'സുരക്ഷിതം',
    warning: 'മുന്നറിയിപ്പ്',
    danger: 'അപകടം',
    
    // Analysis Page
    forensicAnalysis: 'ഫോറൻസിക് വിശകലനം',
    submitContent: 'വിശകലനത്തിനായി ഉള്ളടക്കം സമർപ്പിക്കുക',
    submitDescription: 'ഫയലുകൾ അപ്‌ലോഡ് ചെയ്യുക, ടെക്സ്റ്റ് പേസ്റ്റ് ചെയ്യുക അല്ലെങ്കിൽ URL നൽകുക.',
    upload: 'അപ്‌ലോഡ്',
    text: 'വാചകം',
    url: 'URL',
    clickToUpload: 'അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക',
    fileTypes: 'PNG, JPG, MP4, MOV (പരമാവധി 50MB)',
    pasteText: 'സംശയാസ്പദമായ ടെക്സ്റ്റ്, സന്ദേശങ്ങൾ അല്ലെങ്കിൽ ഉള്ളടക്കം ഇവിടെ പേസ്റ്റ് ചെയ്യുക...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'വിശകലനത്തിനായി ചിത്രം, വീഡിയോ അല്ലെങ്കിൽ വെബ്‌പേജ് സൂചിപ്പിക്കുന്ന URL നൽകുക',
    cancel: 'റദ്ദാക്കുക',
    analyze: 'ഇപ്പോൾ വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    recordVoice: 'ശബ്ദം റെക്കോർഡ് ചെയ്യുക',
    stopRecording: 'റെക്കോർഡിംഗ് നിർത്തുക',
    listening: 'കേൾക്കുന്നു...',
    
    // Results Page
    analysisReport: 'വിശകലന റിപ്പോർട്ട്',
    forensicComplete: 'ഫോറൻസിക് വിശകലനം പൂർത്തിയായി',
    highRisk: 'ഉയർന്ന അപകടസാധ്യത - സാധ്യതയുള്ള തട്ടിപ്പ്',
    highRiskWarning: 'പ്രതികരിക്കരുത് അല്ലെങ്കിൽ വിവരങ്ങൾ പങ്കിടരുത്!',
    mediumRisk: 'ഇടത്തരം അപകടസാധ്യത - ശ്രദ്ധിക്കുക',
    lowRisk: 'കുറഞ്ഞ അപകടസാധ്യത - സുരക്ഷിതമെന്ന് തോന്നുന്നു',
    originClassification: 'ഉത്ഭവ വർഗ്ഗീകരണം',
    confidence: 'ആത്മവിശ്വാസം',
    indicators: 'സൂചകങ്ങൾ',
    scamRisk: 'തട്ടിപ്പ് അപകടസാധ്യത നില',
    patternsDetected: 'പാറ്റേണുകൾ കണ്ടെത്തി',
    evidenceSummary: 'തെളിവ് സംഗ്രഹം',
    signalsDetected: 'സിഗ്നലുകൾ കണ്ടെത്തി',
    forensicNotes: 'ഫോറൻസിക് കുറിപ്പുകൾ',
    reportDetails: 'റിപ്പോർട്ട് വിശദാംശങ്ങൾ',
    reportId: 'റിപ്പോർട്ട് ID',
    timestamp: 'ടൈംസ്റ്റാമ്പ്',
    contentHash: 'ഉള്ളടക്ക ഹാഷ് (SHA-256)',
    recommendedActions: 'ശുപാർശ ചെയ്ത പ്രവർത്തനങ്ങൾ',
    analysisSummary: 'വിശകലന സംഗ്രഹം',
    limitations: 'പരിമിതികൾ',
    readAloud: 'ഉറക്കെ വായിക്കുക',
    shareWhatsApp: 'WhatsApp-ൽ പങ്കിടുക',
    stopReading: 'വായന നിർത്തുക',
    
    // Risk Levels
    highRiskLabel: 'ഉയർന്ന അപകടസാധ്യത',
    mediumRiskLabel: 'ഇടത്തരം അപകടസാധ്യത',
    lowRiskLabel: 'കുറഞ്ഞ അപകടസാധ്യത',
    
    // Toast Messages
    fileSelected: 'ഫയൽ തിരഞ്ഞെടുത്തു',
    selectFile: 'അപ്‌ലോഡ് ചെയ്യാൻ ഒരു ഫയൽ തിരഞ്ഞെടുക്കുക',
    enterText: 'വിശകലനത്തിനായി ടെക്സ്റ്റ് നൽകുക',
    enterUrlText: 'വിശകലനത്തിനായി URL നൽകുക',
    analysisComplete: 'വിശകലനം പൂർത്തിയായി!',
    analysisFailed: 'വിശകലനം പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    unsupportedFile: 'പിന്തുണയ്‌ക്കാത്ത ഫയൽ തരം. PNG, JPG, MP4, അല്ലെങ്കിൽ MOV ഫയലുകൾ അപ്‌ലോഡ് ചെയ്യുക.',
    voiceNotSupported: 'ഈ ബ്രൗസറിൽ വോയിസ് ഇൻപുട്ട് പിന്തുണയ്‌ക്കുന്നില്ല. Chrome അല്ലെങ്കിൽ Edge ഉപയോഗിക്കുക.',
    noSpeechDetected: 'സംഭാഷണം കണ്ടെത്തിയില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    micPermissionDenied: 'മൈക്രോഫോൺ അനുമതി നിരസിച്ചു.',
    voiceInputError: 'വോയിസ് ഇൻപുട്ട് പിശക്. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    voiceOutputError: 'വോയിസ് ഔട്ട്‌പുട്ട് പിശക്. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    recordingStarted: 'റെക്കോർഡിംഗ് ആരംഭിച്ചു. ഇപ്പോൾ സംസാരിക്കുക...',
    recordingStopped: 'റെക്കോർഡിംഗ് നിർത്തി',
    readingAloud: 'ഉറക്കെ വായിക്കുന്നു...',
    readingStopped: 'വായന നിർത്തി',
  },
  pa: {
    // Header
    appTitle: 'VeriSure',
    analyzeNow: 'ਹੁਣੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    newAnalysis: 'ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ',
    
    // Home Page
    heroLabel: 'ਉੱਨਤ AI ਫੋਰੈਂਸਿਕ',
    heroTitle: 'AI ਸਮੱਗਰੀ ਅਤੇ ਧੋਖਾਧੜੀ ਦਾ ਪਤਾ ਲਗਾਓ',
    heroDescription: 'VeriSure AI-ਤਿਆਰ ਸਮੱਗਰੀ ਦੀ ਪਛਾਣ ਕਰਨ ਅਤੇ ਧੋਖਾਧੜੀ ਦੇ ਜੋਖਮ ਦਾ ਮੁਲਾਂਕਣ ਕਰਨ ਲਈ ਫੋਰੈਂਸਿਕ-ਗ੍ਰੇਡ ਵਿਸ਼ਲੇਸ਼ਣ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    safe: 'ਸੁਰੱਖਿਅਤ',
    warning: 'ਚੇਤਾਵਨੀ',
    danger: 'ਖ਼ਤਰਾ',
    
    // Analysis Page
    forensicAnalysis: 'ਫੋਰੈਂਸਿਕ ਵਿਸ਼ਲੇਸ਼ਣ',
    submitContent: 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਸਮੱਗਰੀ ਜਮ੍ਹਾਂ ਕਰੋ',
    submitDescription: 'ਫਾਈਲਾਂ ਅੱਪਲੋਡ ਕਰੋ, ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ ਜਾਂ URL ਪ੍ਰਦਾਨ ਕਰੋ।',
    upload: 'ਅੱਪਲੋਡ',
    text: 'ਟੈਕਸਟ',
    url: 'URL',
    clickToUpload: 'ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    fileTypes: 'PNG, JPG, MP4, MOV (ਵੱਧ ਤੋਂ ਵੱਧ 50MB)',
    pasteText: 'ਇੱਥੇ ਸ਼ੱਕੀ ਟੈਕਸਟ, ਸੁਨੇਹੇ ਜਾਂ ਸਮੱਗਰੀ ਪੇਸਟ ਕਰੋ...',
    enterUrl: 'https://example.com/suspicious-content',
    urlDescription: 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਚਿੱਤਰ, ਵੀਡੀਓ ਜਾਂ ਵੈਬਪੇਜ ਵੱਲ ਇਸ਼ਾਰਾ ਕਰਨ ਵਾਲਾ URL ਦਾਖਲ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    analyze: 'ਹੁਣੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    recordVoice: 'ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ',
    stopRecording: 'ਰਿਕਾਰਡਿੰਗ ਬੰਦ ਕਰੋ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹੈ...',
    
    // Results Page
    analysisReport: 'ਵਿਸ਼ਲੇਸ਼ਣ ਰਿਪੋਰਟ',
    forensicComplete: 'ਫੋਰੈਂਸਿਕ ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ',
    highRisk: 'ਉੱਚ ਜੋਖਮ - ਸੰਭਾਵਿਤ ਧੋਖਾਧੜੀ',
    highRiskWarning: 'ਜਵਾਬ ਨਾ ਦਿਓ ਜਾਂ ਕੋਈ ਜਾਣਕਾਰੀ ਸਾਂਝੀ ਨਾ ਕਰੋ!',
    mediumRisk: 'ਮੱਧਮ ਜੋਖਮ - ਸਾਵਧਾਨ ਰਹੋ',
    lowRisk: 'ਘੱਟ ਜੋਖਮ - ਸੁਰੱਖਿਅਤ ਲੱਗਦਾ ਹੈ',
    originClassification: 'ਮੂਲ ਵਰਗੀਕਰਨ',
    confidence: 'ਭਰੋਸਾ',
    indicators: 'ਸੰਕੇਤਕ',
    scamRisk: 'ਧੋਖਾਧੜੀ ਜੋਖਮ ਪੱਧਰ',
    patternsDetected: 'ਨਮੂਨੇ ਖੋਜੇ ਗਏ',
    evidenceSummary: 'ਸਬੂਤ ਸੰਖੇਪ',
    signalsDetected: 'ਸੰਕੇਤ ਖੋਜੇ ਗਏ',
    forensicNotes: 'ਫੋਰੈਂਸਿਕ ਨੋਟਸ',
    reportDetails: 'ਰਿਪੋਰਟ ਵੇਰਵੇ',
    reportId: 'ਰਿਪੋਰਟ ID',
    timestamp: 'ਟਾਈਮਸਟੈਂਪ',
    contentHash: 'ਸਮੱਗਰੀ ਹੈਸ਼ (SHA-256)',
    recommendedActions: 'ਸਿਫਾਰਸ਼ਿਤ ਕਾਰਵਾਈਆਂ',
    analysisSummary: 'ਵਿਸ਼ਲੇਸ਼ਣ ਸੰਖੇਪ',
    limitations: 'ਸੀਮਾਵਾਂ',
    readAloud: 'ਉੱਚੀ ਪੜ੍ਹੋ',
    shareWhatsApp: 'WhatsApp \'ਤੇ ਸਾਂਝਾ ਕਰੋ',
    stopReading: 'ਪੜ੍ਹਨਾ ਬੰਦ ਕਰੋ',
    
    // Risk Levels
    highRiskLabel: 'ਉੱਚ ਜੋਖਮ',
    mediumRiskLabel: 'ਮੱਧਮ ਜੋਖਮ',
    lowRiskLabel: 'ਘੱਟ ਜੋਖਮ',
    
    // Toast Messages
    fileSelected: 'ਫਾਈਲ ਚੁਣੀ ਗਈ',
    selectFile: 'ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਇੱਕ ਫਾਈਲ ਚੁਣੋ',
    enterText: 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਟੈਕਸਟ ਦਾਖਲ ਕਰੋ',
    enterUrlText: 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ URL ਦਾਖਲ ਕਰੋ',
    analysisComplete: 'ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ!',
    analysisFailed: 'ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    unsupportedFile: 'ਅਸਮਰਥਿਤ ਫਾਈਲ ਕਿਸਮ। PNG, JPG, MP4, ਜਾਂ MOV ਫਾਈਲਾਂ ਅੱਪਲੋਡ ਕਰੋ।',
    voiceNotSupported: 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਵੌਇਸ ਇਨਪੁੱਟ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ। Chrome ਜਾਂ Edge ਵਰਤੋ।',
    noSpeechDetected: 'ਕੋਈ ਬੋਲੀ ਖੋਜੀ ਨਹੀਂ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    micPermissionDenied: 'ਮਾਈਕ੍ਰੋਫੋਨ ਇਜਾਜ਼ਤ ਅਸਵੀਕਾਰ ਕੀਤੀ ਗਈ।',
    voiceInputError: 'ਵੌਇਸ ਇਨਪੁੱਟ ਗਲਤੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    voiceOutputError: 'ਵੌਇਸ ਆਉਟਪੁੱਟ ਗਲਤੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    recordingStarted: 'ਰਿਕਾਰਡਿੰਗ ਸ਼ੁਰੂ ਹੋ ਗਈ। ਹੁਣ ਬੋਲੋ...',
    recordingStopped: 'ਰਿਕਾਰਡਿੰਗ ਬੰਦ ਹੋ ਗਈ',
    readingAloud: 'ਉੱਚੀ ਪੜ੍ਹ ਰਿਹਾ ਹੈ...',
    readingStopped: 'ਪੜ੍ਹਨਾ ਬੰਦ ਹੋ ਗਿਆ',
  }
};

const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳', nativeName: 'தமிழ்' },
  { code: 'bn', name: 'Bengali', flag: '🇮🇳', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', flag: '🇮🇳', nativeName: 'मराठी' },
  { code: 'te', name: 'Telugu', flag: '🇮🇳', nativeName: 'తెలుగు' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', flag: '🇮🇳', nativeName: 'ਪੰਜਾਬੀ' },
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    languages,
    currentLanguage: languages.find(l => l.code === language)
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
